/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    'index',
    {
      type: 'autogenerated',
      dirName: 'pro',
    },
    {
      type: 'autogenerated',
      dirName: 'gento',
    },
    {
      type: 'autogenerated',
      dirName: 'data-converter',
    },
    {
      type: 'category',
      label: 'VLA 入门',
      items: [
        'vla/index',
        'vla/dataset-conversion',
        'vla/dataset-sample',
        'vla/training',
        'vla/deployment',
      ],
    },
    {
      type: 'category',
      label: 'XR 遥操作客户端',
      link: { type: 'doc', id: 'xr-teleop/index' },
      items: [
        'xr-teleop/pico',
        'xr-teleop/meta'
      ]
    },
  ],
};

module.exports = sidebars;
