/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    'index',
    {
      type: 'autogenerated',
      dirName: 'pro',
    },
    {
      type: 'autogenerated',
      dirName: 'gento',
    },
    {
      type: 'autogenerated',
      dirName: 'data-converter',
    },
  ],
};

module.exports = sidebars;
